import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useEffect, useRef, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useCurrentUser } from "./useCurrentUser";
import { showError, showSuccess, showWarning } from "@/utils/toastUtils";
import { logger } from "@/utils/logger";

export type AIInsight = {
  id: string;
  company_id: string;
  insight_text: string;
  insight_type: string;
  data_summary: any;
  created_at: string;
  period_start: string;
  period_end: string;
};

export const useAIInsights = () => {
  const { userData } = useCurrentUser();
  const queryClient = useQueryClient();

  // Fetch latest insight
  const { data: latestInsight, isLoading } = useQuery({
    queryKey: ['ai-insights', 'latest', userData?.company_id],
    queryFn: async () => {
      if (!userData?.company_id) return null;

      const { data, error } = await supabase
        .from('ai_insights')
        .select('id, company_id, insight_text, insight_type, data_summary, created_at, period_start, period_end')
        .eq('company_id', userData.company_id)
        .order('created_at', { ascending: false })
        .limit(1)
        .maybeSingle();

      if (error) throw error;
      return data as AIInsight | null;
    },
    enabled: !!userData?.company_id,
    staleTime: 24 * 60 * 60 * 1000, // 24 hours - daily cache
    refetchOnMount: false,
    refetchOnWindowFocus: false,
    refetchOnReconnect: false,
  });

  // Fetch insight history
  const { data: insightHistory, isLoading: isLoadingHistory } = useQuery({
    queryKey: ['ai-insights', 'history', userData?.company_id],
    queryFn: async () => {
      if (!userData?.company_id) return [];

      const { data, error } = await supabase
        .from('ai_insights')
        .select('id, company_id, insight_text, insight_type, data_summary, created_at, period_start, period_end')
        .eq('company_id', userData.company_id)
        .order('created_at', { ascending: false })
        .limit(10);

      if (error) throw error;
      return data as AIInsight[];
    },
    enabled: !!userData?.company_id,
    staleTime: 24 * 60 * 60 * 1000, // 24 hours - daily cache
    refetchOnMount: false,
    refetchOnWindowFocus: false,
    refetchOnReconnect: false,
  });

  // Generate new insight
  const generateMutation = useMutation({
    mutationFn: async ({ periodDays = 30, silent = false }: { periodDays?: number; silent?: boolean }) => {
      const { data, error } = await supabase.functions.invoke('generate-insights', {
        body: { period_days: periodDays }
      });

      if (error) throw error;

      // Handle specific error cases
      if (data?.error) {
        if (data.error === 'no_data') {
          throw new Error(data.message || 'Yeterli veri yok');
        } else if (data.error === 'rate_limit') {
          throw new Error(data.message || 'AI kullanım limiti aşıldı');
        } else if (data.error === 'payment_required') {
          throw new Error(data.message || 'AI kredisi tükendi');
        }
        throw new Error(data.message || 'Bir hata oluştu');
      }

      return { ...data, silent };
    },
    onSuccess: (data) => {
      // Invalidate and refetch insights
      queryClient.invalidateQueries({ queryKey: ['ai-insights'] });
      
      // Only show toast if not silent (manual generation)
      if (!data?.silent) {
        if (data?.cached) {
          showSuccess('Bugünkü içgörü yüklendi (Cache)');
        } else {
          showSuccess('Yeni içgörü oluşturuldu');
        }
      }
    },
    onError: (error: Error, variables) => {
      logger.error('Error generating insight', error);
      
      // Only show error if not silent (manual generation)
      if (!variables?.silent) {
        if (error.message.includes('limit')) {
          showWarning(error.message);
        } else if (error.message.includes('kredi')) {
          showError(error.message);
        } else if (error.message.includes('veri yok')) {
          showWarning(error.message);
        } else {
          showError('İçgörü oluşturulurken bir hata oluştu');
        }
      }
    },
  });

  // Auto-generate daily insight
  const autoGeneratedRef = useRef<string | null>(null);
  const [currentDay, setCurrentDay] = useState<string>(() => new Date().toISOString().split('T')[0]);

  // Update current day every minute to detect day changes
  useEffect(() => {
    const interval = setInterval(() => {
      const today = new Date().toISOString().split('T')[0];
      if (today !== currentDay) {
        setCurrentDay(today);
        // Reset auto-generated flag when day changes
        autoGeneratedRef.current = null;
      }
    }, 60000); // Check every minute

    return () => clearInterval(interval);
  }, [currentDay]);

  useEffect(() => {
    const todayKey = new Date().toISOString().split('T')[0];
    
    // Skip if already generated today or still loading
    if (autoGeneratedRef.current === todayKey || isLoading || !userData?.company_id) {
      return;
    }

    // Check if we have today's insight
    if (latestInsight) {
      const insightDate = new Date(latestInsight.created_at).toISOString().split('T')[0];
      if (insightDate === todayKey) {
        // Already have today's insight, mark as checked
        autoGeneratedRef.current = todayKey;
        return;
      }
    }

    // No insight for today, generate automatically (silently)
    if (!generateMutation.isPending && latestInsight !== undefined) {
      logger.info('Auto-generating daily AI insight');
      autoGeneratedRef.current = todayKey;
      generateMutation.mutate({ periodDays: 30, silent: true });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [latestInsight, isLoading, generateMutation.isPending, userData?.company_id, currentDay]);

  return {
    latestInsight,
    insightHistory,
    isLoading,
    isLoadingHistory,
    generateInsight: (params?: { periodDays?: number }) => generateMutation.mutate({ ...params, silent: false }),
    isGenerating: generateMutation.isPending,
  };
};
