
export interface Customer {
  id: string;
  name: string;
  email: string | null;
  mobile_phone: string | null;
  office_phone: string | null;
  company: string | null;
  type: "bireysel" | "kurumsal";
  status: "aktif" | "pasif" | "potansiyel";
  representative: string | null;
  employees?: {
    id: string;
    first_name: string;
    last_name: string;
    position: string;
  } | null;
  balance: number;
  address: string | null;
  city: string | null;
  district: string | null;
  country: string | null;
  postal_code: string | null;
  apartment_number: string | null;
  unit_number: string | null;
  fax: string | null;
  website: string | null;
  bank_name: string | null;
  iban: string | null;
  account_number: string | null;
  trade_registry_number: string | null;
  mersis_number: string | null;
  tax_number: string | null;
  tax_office: string | null;
  is_einvoice_mukellef: boolean;
  einvoice_alias_name: string | null;
  company_id: string | null;
  establishment_date: string | null;
  sector: string | null;
  customer_segment: string | null;
  customer_source: string | null;
  notes: string | null;
  first_contact_position: string | null;
  second_contact_name: string | null;
  second_contact_email: string | null;
  second_contact_phone: string | null;
  second_contact_position: string | null;
  second_address: string | null;
  second_city: string | null;
  second_district: string | null;
  second_country: string | null;
  second_postal_code: string | null;
  payment_terms: string | null;
  created_at: string;
  updated_at: string;
}

export interface CustomerFormData {
  name: string;
  email: string;
  mobile_phone: string;
  office_phone: string;
  company: string;
  type: "bireysel" | "kurumsal";
  status: "aktif" | "pasif" | "potansiyel";
  representative: string;
  balance: number;
  address: string;
  tax_number: string;
  tax_office: string;
  city: string;
  district: string;
  apartment_number: string;
  unit_number: string;
  einvoice_alias_name: string;
  website: string;
  country: string;
  postal_code: string;
  fax: string;
  bank_name: string;
  iban: string;
  account_number: string;
  trade_registry_number: string;
  mersis_number: string;
  establishment_date: string;
  sector: string;
  customer_segment: string;
  customer_source: string;
  notes: string;
  first_contact_position: string;
  second_contact_name: string;
  second_contact_email: string;
  second_contact_phone: string;
  second_contact_position: string;
  second_address: string;
  second_city: string;
  second_district: string;
  second_country: string;
  second_postal_code: string;
  payment_terms: string;
  is_einvoice_mukellef?: boolean; // E-fatura mükellefi durumu (formda gösterilmez, otomatik set edilir)
}
