// This file is automatically generated. Do not edit it directly.
// @ts-nocheck
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Environment variables'dan oku
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing required Supabase environment variables: VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY must be set');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create basic supabase client without auth
const createCustomSupabaseClient = () => {
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce', // PKCE flow for better security and CORS handling
      redirectTo: typeof window !== 'undefined' ? window.location.origin : undefined,
    },
    global: {
      headers: {
        'X-Client-Info': 'ngs-app',
      },
      fetch: (url, options = {}) => {
        return fetch(url, {
          ...options,
          headers: {
            ...options.headers,
            'apikey': SUPABASE_PUBLISHABLE_KEY,
          },
        });
      },
    }
  });
};

export const supabase = createCustomSupabaseClient();

