// This file is automatically generated. Do not edit it directly.
// @ts-nocheck
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Supabase project configuration from environment variables
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Supabase environment variables. Please check your .env file.\n' +
    'Required: VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create basic supabase client without auth
const createCustomSupabaseClient = () => {
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce', // PKCE flow for better security and CORS handling
      redirectTo: typeof window !== 'undefined' ? window.location.origin : undefined,
      storage: typeof window !== 'undefined' ? window.localStorage : undefined,
      storageKey: `sb-${new URL(SUPABASE_URL).hostname.split('.')[0]}-auth-token`,
    },
    global: {
      headers: {
        'X-Client-Info': 'ngs-app',
      },
    }
  });
};

export const supabase = createCustomSupabaseClient();

