import { TemplateSchema } from '@/types/pdf-template';

export const defaultTemplateValues: TemplateSchema = {
  page: {
    size: 'A4',
    padding: { top: 40, right: 40, bottom: 40, left: 40 },
    fontSize: 12,
    fontFamily: 'Roboto',
    fontWeight: 'normal',
    fontColor: '#000000',
    backgroundColor: '#FFFFFF',
    backgroundImage: '',
    backgroundStyle: 'none',
    backgroundStyleColor: '#4F46E5',
    backgroundOpacity: 5,
  },
  header: {
    showTitle: true,
    title: 'TEKLİF',
    titleFontSize: 16,
    showLogo: true,
    logoUrl: undefined,
    logoPosition: 'left',
    logoSize: 80,
    showValidity: true,
    showCompanyInfo: true,
    companyName: '',
    companyAddress: '',
    companyPhone: '',
    companyEmail: '',
    companyWebsite: '',
    companyTaxNumber: '',
    companyInfoFontSize: 10,
  },
  customer: {
    customerTitleFontSize: 12,
    customerInfoFontSize: 10,
  },
  lineTable: {
    columns: [
      { key: 'product_image', show: true, label: 'Görsel', align: 'center' },
      { key: 'description', show: true, label: 'Açıklama', align: 'left' },
      { key: 'quantity', show: true, label: 'Miktar', align: 'center' },
      { key: 'unit_price', show: true, label: 'Birim Fiyat', align: 'right' },
      { key: 'discount', show: true, label: 'İndirim', align: 'right' },
      { key: 'total', show: true, label: 'Toplam', align: 'right' },
    ],
    showRowNumber: true,
  },
  totals: {
    showGross: true,
    showDiscount: true,
    showTax: true,
    showNet: true,
  },
  notes: {
    footer: 'İyi çalışmalar dileriz.',
    footerFontSize: 12,
    showFooterLogo: true,
    footerLogoSize: 40,
    termsSettings: {
      showPaymentTerms: true,
      showDeliveryTerms: true,
      showWarrantyTerms: true,
      showPriceTerms: false,
      showOtherTerms: false,
      titleAlign: 'left',
    },
  },
  signatures: {
    show: true,
    showTechnician: true,
    showCustomer: true,
    technicianLabel: 'Çalışan',
    customerLabel: 'Müşteri',
    fontSize: 10,
  },
};

